version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/lib/pq
    versions:
    - 1.10.0
  - dependency-name: github.com/jmoiron/sqlx
    versions:
    - 1.3.1
